### ISSUE TITLE
Creating a contributor.md file

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/first_contribution#5]
We need to create a contributor file where all the contributors would be mention!

**Comment by onelifefyi** [comment]
I've created PR having contributors.md file with alphabetically sorted names along with link to their profile :)

**Comment by sudipt1999** [comment]
Thanks ! One thing always mention link to pr in issue and kindly put the issue number in pr!

**Comment by onelifefyi** [comment]
Thanks! I'll remember that 😊
