### ISSUE TITLE
Create a web page for the cheatsheet !

### ISSUE THREAD

**Issue by sudipt1999** [sudipt1999/first_contribution#8]
Create a web page for the cheat sheet

**Comment by avijeetpandey** [comment]
what kind of web page and how can I contribute?

**Comment by sudipt1999** [comment]
@Avijeetpandey25  simple html css page where all the cheats in gitcheatsheet is mention ! A beautiful UI website basically ! Can be easily created with bootstrap in few hours!

**Comment by avijeetpandey** [comment]
sure should I make a separate folder in the same repo for that ....also I want to add something to the gitcheatsheet file should I do it?

**Comment by sudipt1999** [comment]
I would suggest creating different branches for each work, that way it wont mix up !
for website kindly add to root folder but make folder for js and css files since i will directly host it to github pages ! and sure u can add to githubcheat sheet there are issues related to it ! Hope you enjoy working on them!

**Comment by avijeetpandey** [comment]
of course in a different branch , thanx, for the guidance ..ill make sure ill do my best. You are doing a great job.

**Comment by sudipt1999** [comment]
Thanks for your support!

**Comment by avijeetpandey** [comment]
My pleasure just made my first pull request, have a look. After that, I will work on the webpage.
